build_from:
  aarch64: "registry.cn-hangzhou.aliyuncs.com/library/homeassistant/aarch64-base:3.19"
  amd64: "registry.cn-hangzhou.aliyuncs.com/library/homeassistant/amd64-base:3.19"
  armv7: "registry.cn-hangzhou.aliyuncs.com/library/homeassistant/armv7-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Fusion"
  org.opencontainers.image.description: "A modern, easy-to-use and performant custom Home Assistant dashboard"
  org.opencontainers.image.source: "https://github.com/symi-daguo/addon-ha-fusion"
  org.opencontainers.image.licenses: "MIT"