# required configuration options
name: "HA Fusion"
version: "2024.12.0"
slug: "ha_fusion"
description: "一个现代化、易用且高性能的 Home Assistant 自定义仪表盘"
url: "https://github.com/symi-daguo/addon-ha-fusion"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: http://[HOST]:[PORT:8099]
options: {}
schema: {}
