version: '3'
services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/matt8707/ha-fusion:latest
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - HASS_URL=http://frp.hasskit.com:30000
    restart: always
