services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/symi-daguo/ha-fusion:latest
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - HASS_URL=http://192.168.2.12:8123
    restart: always
